//! Keeps the vault-root `AGENTS.md` present and current. The content is
//! single-sourced from the published docs page (`agents/vault` on the docs
//! site, which also feeds `/llms.txt`); embedding it here makes moving or
//! deleting that page a compile error rather than silent drift.

use std::path::Path;

const RAW: &str = include_str!("../../../docs/src/content/docs/agents/vault.md");

const NOTICE: &str = "# Loofah vault\n\n\
This file is auto-regenerated by the app and by `loof doctor`; manual edits\n\
are replaced (the previous copy is kept in `.trash/`). Canonical page:\n\
https://loofah.io/agents/vault/\n";

/// The vault copy of the docs page: Starlight frontmatter replaced by a
/// generated-file notice, since the vault file has no site chrome to carry
/// the title or the regeneration warning.
pub fn agents_doc_content() -> String {
    let body = RAW
        .strip_prefix("---")
        .and_then(|rest| rest.split_once("\n---\n"))
        .map(|(_, body)| body)
        .unwrap_or(RAW)
        .trim_start();
    format!("{NOTICE}\n{body}")
}

/// Writes `<vault_base>/AGENTS.md` if missing or stale. Returns `Ok(true)`
/// when the file was (re)written, `Ok(false)` when it was already current.
pub fn ensure_agents_doc(vault_base: &Path) -> hypr_fs_sync_core::Result<bool> {
    let path = vault_base.join("AGENTS.md");
    let tmp_path = hypr_fs_sync_core::export::tmp_sibling_path(&path);
    hypr_fs_sync_core::export::write_file_atomic(
        vault_base,
        &path,
        &tmp_path,
        agents_doc_content().as_bytes(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_guidance_prefers_typed_session_interfaces() {
        let content = agents_doc_content();

        for tool in ["list_meetings", "get_meeting", "get_meeting_transcript"] {
            assert!(content.contains(tool));
        }

        assert!(content.contains("loof --json sessions list"));
        assert!(!content.contains("--base ."));
        assert!(content.contains("--vault-path ABSOLUTE_VAULT_DIR"));
        assert!(content.contains("Do not use `find`,"));
        assert!(content.contains("direct SQLite queries"));
    }

    #[test]
    fn generated_content_documents_the_vault_contract() {
        let content = agents_doc_content();

        for marker in [
            "sessions/<id>/",
            "_meta.json",
            "notes.md",
            "enhanced/",
            "attachments/",
            ".trash/",
            "loof doctor",
            "user attachment",
        ] {
            assert!(content.contains(marker), "missing `{marker}`");
        }
    }

    #[test]
    fn generated_content_is_standalone_markdown() {
        let content = agents_doc_content();

        assert!(content.starts_with("# Loofah vault"));
        assert!(!content.contains("\n---\n"));
        assert!(!content.contains("title:"));
        assert!(!content.contains("import "));
    }

    #[test]
    fn ensure_writes_once_and_trashes_edits() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("AGENTS.md");

        assert!(ensure_agents_doc(dir.path()).unwrap());
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            agents_doc_content()
        );

        assert!(!ensure_agents_doc(dir.path()).unwrap());

        std::fs::write(&path, "user edit").unwrap();
        assert!(ensure_agents_doc(dir.path()).unwrap());
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            agents_doc_content()
        );

        let trash = dir.path().join(".trash");
        let trashed: Vec<_> = walk_files(&trash);
        assert_eq!(trashed.len(), 1);
        assert_eq!(std::fs::read_to_string(&trashed[0]).unwrap(), "user edit");
    }

    fn walk_files(root: &Path) -> Vec<std::path::PathBuf> {
        let mut files = Vec::new();
        let mut stack = vec![root.to_path_buf()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(dir).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    stack.push(path);
                } else {
                    files.push(path);
                }
            }
        }
        files
    }
}
