// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listMeetings(input: ListMeetingsInput) : Promise<Result<MeetingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|list_meetings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeeting(input: GetMeetingInput) : Promise<Result<Meeting, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeetingTranscript(input: GetMeetingTranscriptInput) : Promise<Result<TranscriptPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting_transcript", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async execute(sql: string, params: JsonValue[]) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute", { sql, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeTransaction(statements: TransactionStatement[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_transaction", { statements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeProxy(sql: string, params: JsonValue[], method: string) : Promise<Result<ExecuteProxyResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_proxy", { sql, params, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async subscribe(sql: string, params: JsonValue[], onEvent: TAURI_CHANNEL<QueryEvent>) : Promise<Result<SubscriptionRegistration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|subscribe", { sql, params, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribe(subscriptionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|unsubscribe", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionItem = { id: string; assignee_human_id: string; status: string; text: string; due_at: string; completed_at: string | null }
export type DependencyAnalysis = { kind: "reactive"; data: { targets: DependencyTarget[] } } | { kind: "non_reactive"; data: { reason: string } }
export type DependencyTarget = { kind: "table"; data: string } | { kind: "virtual_table"; data: string }
export type Document = { id: string; kind: string; template_id: string; title: string; markdown: string; sort_order: number; updated_at: string }
export type ExecuteProxyResult = { rows: JsonValue[] }
export type GetMeetingInput = { meeting_id: string }
export type GetMeetingTranscriptInput = { meeting_id: string; offset: number | null; limit: number | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ListMeetingsInput = { query: string | null; limit: number | null; offset: number | null }
export type Meeting = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string; timezone: string; language: string; note: Document | null; summaries: Document[]; action_items: ActionItem[] }
export type MeetingListItem = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string }
export type MeetingPage = { meetings: MeetingListItem[]; pagination: Pagination }
export type Pagination = { offset: number; limit: number; returned: number; total: number | null; next_offset: number | null }
export type QueryEvent = { event: "result"; data: JsonValue[] } | { event: "error"; data: string }
export type SubscriptionRegistration = { id: string; analysis: DependencyAnalysis }
export type TAURI_CHANNEL<TSend> = null
export type TransactionStatement = { sql: string; params: JsonValue[]; expectedRowsAffected?: number | null }
export type TranscriptPage = { meeting_id: string; text: string; words: JsonValue[]; pagination: Pagination }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
