// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async getOnboardingNeeded(): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_onboarding_needed"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setOnboardingNeeded(v: boolean): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_onboarding_needed", { v }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getDismissedToasts(): Promise<Result<string[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_dismissed_toasts") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setDismissedToasts(v: string[]): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_dismissed_toasts", { v }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getEnv(key: string): Promise<string> {
    return await TAURI_INVOKE("get_env", { key });
  },
  async showDevtool(): Promise<boolean> {
    return await TAURI_INVOKE("show_devtool");
  },
  async completeAppExit(): Promise<void> {
    await TAURI_INVOKE("complete_app_exit");
  },
  async getPinnedTabs(): Promise<Result<string | null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_pinned_tabs") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setPinnedTabs(v: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_pinned_tabs", { v }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getRecentlyOpenedSessions(): Promise<Result<string | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_recently_opened_sessions"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setRecentlyOpenedSessions(v: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_recently_opened_sessions", { v }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async checkEmbeddedCli(): Promise<Result<EmbeddedCliStatus, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("check_embedded_cli") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async installEmbeddedCli(): Promise<Result<EmbeddedCliStatus, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("install_embedded_cli") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionWriteMeta(meta: SessionMeta): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_write_meta", { meta }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionUpdateMeta(
    sessionId: string,
    patch: SessionMetaPatch,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_update_meta", { sessionId, patch }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionWriteNote(
    sessionId: string,
    markdown: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_write_note", { sessionId, markdown }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionReadNote(
    sessionId: string,
  ): Promise<Result<string | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_read_note", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionWriteDocument(
    sessionId: string,
    kind: string,
    markdown: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_write_document", {
          sessionId,
          kind,
          markdown,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionWriteEnhancedDoc(
    doc: EnhancedDoc,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_write_enhanced_doc", { doc }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionUpdateEnhancedDoc(
    sessionId: string,
    docId: string,
    patch: EnhancedDocPatch,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_update_enhanced_doc", {
          sessionId,
          docId,
          patch,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionDeleteEnhancedDoc(
    sessionId: string,
    docId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_delete_enhanced_doc", {
          sessionId,
          docId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionListTasks(
    sourceType: string,
    sourceId: string,
  ): Promise<Result<TaskItem[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_list_tasks", {
          sourceType,
          sourceId,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionReplaceTasks(
    sourceType: string,
    sourceId: string,
    tasks: TaskInput[],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_replace_tasks", {
          sourceType,
          sourceId,
          tasks,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionRemoveTasks(
    sourceType: string,
    sourceId: string,
    taskIds: string[],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_remove_tasks", {
          sourceType,
          sourceId,
          taskIds,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionMoveTasks(
    taskIds: string[],
    sourceType: string,
    sourceId: string,
    insertionOrder: number,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_move_tasks", {
          taskIds,
          sourceType,
          sourceId,
          insertionOrder,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionAppendTranscript(
    sessionId: string,
    delta: TranscriptDelta,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_append_transcript", {
          sessionId,
          delta,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionFlushTranscript(
    sessionId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_flush_transcript", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionWriteTranscript(
    sessionId: string,
    transcript: TranscriptWithData,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_write_transcript", {
          sessionId,
          transcript,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionDelete(sessionId: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_delete", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionRestore(sessionId: string): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_restore", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionRebuildIndex(): Promise<Result<RebuildReport, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_rebuild_index"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionStoreAudio(
    sessionId: string,
    sourcePath: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_store_audio", {
          sessionId,
          sourcePath,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionListAudio(sessionId: string): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_list_audio", { sessionId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async sessionDeleteAudio(
    sessionId: string,
    filename: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("session_delete_audio", {
          sessionId,
          filename,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type EmbeddedCliState =
  | "installed"
  | "missing"
  | "conflict"
  | "unsupported"
  | "resource_missing";
export type EmbeddedCliStatus = {
  supported: boolean;
  commandName: string;
  installPath: string;
  state: EmbeddedCliState;
  details: string | null;
};
/**
 * One AI-generated document (`summary` or `template_output`), file-canonical at
 * `sessions/<session_id>/enhanced/<id>.md`. `id` is the same UUID the `session_documents`
 * index row uses, and the frontmatter carries every metadata column that row mirrors --
 * there is deliberately no sidecar file.
 */
export type EnhancedDoc = {
  id: string;
  session_id: string;
  /**
   * "summary" (no template) or "template_output".
   */
  kind: string;
  title: string;
  template_id: string;
  sort_order: number;
  /**
   * Body only -- never includes the frontmatter block.
   */
  markdown: string;
};
/**
 * Partial update for an existing enhanced doc: `None` means "leave as-is". The `expected_*`
 * fields are compare-and-swap guards against the *current file content* -- a mismatch
 * returns `StoreError::Conflict` and changes nothing, which is the store-level equivalent
 * of the SQL era's `expectedRowsAffected`/`WHERE title = ?` rejections.
 */
export type EnhancedDocPatch = {
  kind?: string | null;
  title?: string | null;
  template_id?: string | null;
  sort_order?: number | null;
  markdown?: string | null;
  expected_title?: string | null;
  expected_markdown?: string | null;
};
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | Partial<{ [key in string]: JsonValue }>;
/**
 * Summary of a `rebuild_index`/`refresh_session` pass. Counts reflect rows *upserted* this
 * pass, not the resulting table size. `errors` never aborts the scan -- an unparseable file
 * is logged here and its existing index row is left untouched (see the hard rule in each
 * match arm below: corruption must never look like deletion).
 */
export type RebuildReport = {
  sessions: number;
  /**
   * Upserted `session_documents` rows this pass -- every `<kind>.md` file including the
   * note (`_memo.md`) and every `enhanced/<doc_id>.md` doc, not just the note.
   */
  notes: number;
  transcripts: number;
  /**
   * Folder ids that have at least one recognized content file (a `<kind>.md` document or
   * `transcript.json`) but no `_meta.json` -- left deliberately unindexed; files untouched.
   */
  ghost_sessions: string[];
  errors: string[];
};
export type SessionMeta = {
  id: string;
  title: string;
  started_at: string | null;
  ended_at: string | null;
  created_at: string;
  tags: string[];
  /**
   * Opaque calendar-event envelope (the sessions row's `event_json`). The store never
   * inspects its interior -- it round-trips whatever JSON the frontend hands it.
   */
  event?: JsonValue | null;
  folder?: string | null;
};
/**
 * Partial update for `_meta.json`: `None` means "leave as-is", so callers can patch a single
 * field without knowing the rest. There is deliberately no way to clear a field back to
 * absent -- no mutation site needs that today.
 */
export type SessionMetaPatch = {
  title?: string | null;
  started_at?: string | null;
  ended_at?: string | null;
  created_at?: string | null;
  tags?: string[] | null;
  event?: JsonValue | null;
  folder?: string | null;
};
/**
 * What the frontend sends on a write: source coordinates come from the command arguments,
 * timestamps and `assignee` are managed store-side (preserved from the existing entry when
 * the task already exists).
 */
export type TaskInput = {
  id: string;
  source_order: number;
  status: string;
  text: string;
  body: JsonValue;
  due_at?: string;
};
/**
 * One action item, file-canonical in `sessions/<session_id>/tasks.json` (or the vault-root
 * `tasks.json` for a source that cannot be tied to a session). Mirrors the live columns of
 * the legacy `action_items` table minus ownership (`owner_user_id`/`created_by`/
 * `updated_by`, dropped per plan decision D10) and minus `deleted_at` -- deletion removes
 * the entry and the list is rewritten atomically.
 */
export type TaskItem = {
  id: string;
  /**
   * "session_raw_note" (source_id is the session id) or "enhanced_note" (source_id is
   * the enhanced doc id). Stored verbatim for any other value.
   */
  source_type: string;
  source_id: string;
  source_order: number;
  /**
   * "todo" | "in_progress" | "done". Stored verbatim; the frontend validates on read.
   */
  status: string;
  /**
   * Plain-text preview of the first paragraph, kept alongside the body like the old
   * `text` column so the file is greppable.
   */
  text: string;
  /**
   * The TipTap `JSONContent[]` body, stored as real JSON (the old `body_json` column
   * held it stringified).
   */
  body: JsonValue;
  due_at?: string;
  assignee?: string;
  created_at: string;
  updated_at: string;
};
export type TranscriptDelta = {
  transcript_id: string;
  new_words: TranscriptWord[];
  replaced_ids: string[];
  new_hints: TranscriptSpeakerHint[];
  started_at_ms: number;
};
export type TranscriptSpeakerHint = {
  id?: string | null;
  word_id: string;
  type: string;
  value?: JsonValue;
};
export type TranscriptWithData = {
  id: string;
  user_id?: string;
  created_at?: string;
  session_id: string;
  started_at?: number;
  ended_at?: number | null;
  memo_md?: string;
  words?: TranscriptWord[];
  speaker_hints?: TranscriptSpeakerHint[];
};
export type TranscriptWord = {
  id?: string | null;
  text: string;
  start_ms: number;
  end_ms: number;
  channel: number;
  speaker?: string | null;
  metadata?: Partial<{ [key in string]: JsonValue }> | null;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
