name: desktop-e2e

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - uses: ./.github/actions/install_desktop_deps
        with:
          target: linux
      - uses: ./.github/actions/rust_install
        with:
          platform: linux
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - run: pnpm -F desktop tauri build --no-bundle --target x86_64-unknown-linux-gnu --config ./src-tauri/tauri.conf.staging.json --features devtools
        env:
          CI: false
      - uses: ./.github/actions/desktop-e2e-linux
        with:
          channel: staging
          target_triple: x86_64-unknown-linux-gnu
