name: zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
      - run: uvx zizmor --min-severity high .github/workflows/
